app.name=Balatro Lite
app.application_id=io.github.guandor.balatrolite
app.orientation=landscape
app.version_code=1
app.version_name=dev

android.enableJetifier=false
android.useAndroidX=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true
